apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: b9qkytzur-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-3e93125a76.un84.p3.openshiftapps.com/rhtap/rhtap-qe:12e423230128491d1a262fbc9e1a3cdc3b3e941b@sha256:e69cead50a8ae993ba21ab06d9885d1aed7905b0e59fbdc0b0f851613027ed63
        name: container-image  
